# Generated by Django 3.0.3 on 2022-01-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccined',
            new_name='Vaccine',
        ),
    ]
